/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.employee;

import Controller.incomeController;
import DBConnection.DatabaseConnection;
import View.SignUI;
import View.manager.EmployeeUI;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DBAccess.incomeAccess;
import Models.income;


/**
 *
 * @author Dimantha
 */
public class watchpayment extends javax.swing.JFrame {

    DatabaseConnection ob;
    float Uprice = 0.0f,ProdTot = 0.0f;
    int Availqty = 0;
    static float GrandTotal = 0.0f;
    income obj;
    incomeController objC;
    
    public watchpayment() {
        initComponents();
        
        objC = new incomeController();
        ob = new DatabaseConnection();
        
        try {
            ResultSet rs = ob.ShowExecuteQuery("SELECT * FROM watch");
            
            while(rs.next()){
                String WatchID = rs.getString("watchID");
                String Bname = rs.getString("BrandName");
                String Price = String.valueOf(rs.getFloat("Price"));
                String qut = String.valueOf(rs.getInt("Quantity"));
                
                String tbData[] = {WatchID ,Bname ,Price,qut};
                DefaultTableModel tableModel = (DefaultTableModel)watchTable.getModel();
                
                tableModel.addRow(tbData);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ResultSet rs = ob.ShowExecuteQuery("SELECT * FROM spareparts");
            
            while(rs.next()){
                String id = rs.getString("code");
                String BnameS = rs.getString("BrandName");
                String Price = String.valueOf(rs.getFloat("Price"));
                String qutS = String.valueOf(rs.getInt("Quantity"));
                
                String tbData[] = {id ,BnameS ,Price, qutS};
                DefaultTableModel tableModel = (DefaultTableModel)partTable.getModel();
                
                tableModel.addRow(tbData);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        watchID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        watchTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        priceW = new javax.swing.JTextField();
        AddToBill = new javax.swing.JButton();
        qut = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        partTable = new javax.swing.JTable();
        code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bname1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        qut1 = new javax.swing.JTextField();
        clear1 = new javax.swing.JButton();
        billAdd = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        billText = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        grandTot = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(7, 36, 61));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("WATCH ID");

        watchID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        watchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("BRAND NAME");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("QUANTITY");

        Bname.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 27)); // NOI18N
        jLabel8.setText("WATCH LIST");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        watchTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        watchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "WATCH ID", "BRAND NAME", "PRICE", "QUANTITY"
            }
        ));
        watchTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        watchTable.setRowHeight(25);
        watchTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        watchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                watchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(watchTable);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("PRICE");

        priceW.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        priceW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceWActionPerformed(evt);
            }
        });

        AddToBill.setBackground(new java.awt.Color(7, 36, 61));
        AddToBill.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AddToBill.setForeground(new java.awt.Color(255, 255, 255));
        AddToBill.setText("ADD TO BILL");
        AddToBill.setBorder(null);
        AddToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBillActionPerformed(evt);
            }
        });

        qut.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qutActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(7, 36, 61));
        clear.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        partTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        partTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "BRAND NAME", "PRICE", "QUANTITY"
            }
        ));
        partTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        partTable.setRowHeight(25);
        partTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        partTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(partTable);

        code.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("CODE");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("BRAND NAME");

        Bname1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Bname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bname1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("PRICE");

        priceS.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        priceS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 27)); // NOI18N
        jLabel10.setText("SPARE PARTS LIST");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("QUANTITY");

        qut1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qut1ActionPerformed(evt);
            }
        });

        clear1.setBackground(new java.awt.Color(7, 36, 61));
        clear1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        clear1.setForeground(new java.awt.Color(255, 255, 255));
        clear1.setText("CLEAR");
        clear1.setBorder(null);
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        billAdd.setBackground(new java.awt.Color(7, 36, 61));
        billAdd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        billAdd.setForeground(new java.awt.Color(255, 255, 255));
        billAdd.setText("ADD TO BILL");
        billAdd.setBorder(null);
        billAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billAddActionPerformed(evt);
            }
        });

        billText.setColumns(20);
        billText.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        billText.setRows(5);
        billText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billTextMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(billText);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 27)); // NOI18N
        jLabel13.setText("RECEIPT PAYMENT ");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        print.setBackground(new java.awt.Color(7, 36, 61));
        print.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT");
        print.setBorder(null);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        grandTot.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        grandTot.setText("RS :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(billAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Bname1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceS, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qut1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(watchID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qut, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceW, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(grandTot, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel13)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(watchID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceW, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bname1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qut1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))))
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grandTot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Users\\Dimantha\\Desktop\\MicrosoftTeams-image (4).png")); // NOI18N
        jLabel9.setText("TimeTicker");

        close.setFont(new java.awt.Font("Calibri", 1, 27)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("BACK");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize)
                .addGap(18, 18, 18)
                .addComponent(close)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(logoutButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void billAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billAddActionPerformed
        if(code.getText().isEmpty() || qut1.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane," Fill the all details...!", "Alart", 2);
        }
        
        else if(Availqty <= Integer.valueOf(qut1.getText())){
            JOptionPane.showMessageDialog(rootPane," Not Enough In Stock ", "Alart", 2);
        }
        
        else{
            ProdTot = Uprice * (float)Integer.valueOf(qut1.getText());
            GrandTotal = GrandTotal + ProdTot;
            i++;
            if(i == 1)
            {
                billText.setText(billText.getText()+" =============> TimeTickerWatches <============= \n ~~~~~~~~~~~~~> 2022.06.28 <~~~~~~~~~~~~~ \nJaffna...\n\n"+"NO      ID      BRAND      PRICE      QUANTITY      TOTAL\n"+i+"      "+code.getText()+"     "+Bname1.getText()+"     "+priceS.getText()+"     "+qut1.getText()+"     "+ProdTot+"\n");
            }
            else{
                billText.setText(billText.getText()+i+"      "+code.getText()+"     "+Bname1.getText()+"     "+priceS.getText()+"     "+qut1.getText()+"     "+ProdTot+"\n");
            }
            grandTot.setText("RS : "+GrandTotal);
        }
        obj = objC.addIncome(code.getText(), Bname1.getText(), Integer.valueOf(qut1.getText()), ProdTot);
        
        boolean result = objC.addincomeDB(obj);
    }//GEN-LAST:event_billAddActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        code.setText("");
        Bname1.setText("");
        priceS.setText("");
        qut1.setText("");
    }//GEN-LAST:event_clear1ActionPerformed

    private void qut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qut1ActionPerformed

    private void priceSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceSActionPerformed

    private void Bname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bname1ActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        watchID.setText("");
        Bname.setText("");
        priceW.setText("");
        qut.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void qutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qutActionPerformed

    private void AddToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBillActionPerformed
        if(watchID.getText().isEmpty() || qut.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane," Fill the all details...!", "Alart", 2);
        }
        
        else if(Availqty <= Integer.valueOf(qut.getText())){
            JOptionPane.showMessageDialog(rootPane," Not Enough In Stock ", "Alart", 2);
        }
        else{
            ProdTot = Uprice * (float)Integer.valueOf(qut.getText());
            GrandTotal =  GrandTotal + ProdTot;
            i++;
            if(i == 1)
            {
                billText.setText(billText.getText()+" =============> TimeTickerWatches <============= \n\n"+"NO    ID    BRAND    PRICE    QUANTITY    TOTAL\n"+i+"      "+watchID.getText()+"     "+Bname.getText()+"     "+priceW.getText()+"     "+qut.getText()+"     "+ProdTot+"\n");
            }
            else{
                billText.setText(billText.getText()+i+"      "+watchID.getText()+"     "+Bname.getText()+"     "+priceW.getText()+"     "+qut.getText()+"     "+ProdTot+"\n");
            }
            grandTot.setText("RS : "+GrandTotal);
        }
        
        obj = objC.addIncome(watchID.getText(), Bname.getText(), Integer.valueOf(qut.getText()), ProdTot);
        
        boolean result = objC.addincomeDB(obj);
    }//GEN-LAST:event_AddToBillActionPerformed

    private void priceWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceWActionPerformed

    private void watchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)watchTable.getModel();
        int Myindex = watchTable.getSelectedRow();

        watchID.setText(model.getValueAt(Myindex, 0).toString());
        Bname.setText(model.getValueAt(Myindex, 1).toString());
        priceW.setText(model.getValueAt(Myindex, 2).toString());
        
        Availqty = Integer.valueOf(model.getValueAt(Myindex, 3).toString());
        
        Uprice = Float.valueOf(model.getValueAt(Myindex, 2).toString());

    }//GEN-LAST:event_watchTableMouseClicked

    private void BnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BnameActionPerformed

    private void watchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchIDActionPerformed

    private void partTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)partTable.getModel();
        int Myindex = partTable.getSelectedRow();
        
        code.setText(model.getValueAt(Myindex, 0).toString());
        Bname1.setText(model.getValueAt(Myindex, 1).toString());
        priceS.setText(model.getValueAt(Myindex, 2).toString());
        
        Availqty = Integer.valueOf(model.getValueAt(Myindex, 3).toString());
        Uprice = Float.valueOf(model.getValueAt(Myindex, 2).toString());

    }//GEN-LAST:event_partTableMouseClicked

    private void billTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_billTextMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try{
            billText.print();
        }
        catch(Exception e){
             
        }
    }//GEN-LAST:event_printActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(HIDE_ON_CLOSE);
    }//GEN-LAST:event_minimizeMouseClicked

    static int i = 0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(watchpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(watchpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(watchpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(watchpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new watchpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToBill;
    private javax.swing.JTextField Bname;
    private javax.swing.JTextField Bname1;
    private javax.swing.JButton billAdd;
    private javax.swing.JTextArea billText;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear1;
    private javax.swing.JLabel close;
    private javax.swing.JTextField code;
    private javax.swing.JLabel grandTot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JLabel minimize;
    private javax.swing.JTable partTable;
    private javax.swing.JTextField priceS;
    private javax.swing.JTextField priceW;
    private javax.swing.JButton print;
    private javax.swing.JTextField qut;
    private javax.swing.JTextField qut1;
    private javax.swing.JTextField watchID;
    private javax.swing.JTable watchTable;
    // End of variables declaration//GEN-END:variables
}
